name: build-go-binary

on:
  release:
    types: [created] # 表示在创建新的 Release 时触发

permissions:
  contents: write
  packages: write

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        # 386 amd64 arm arm64 s390x loong64
        goarch: [amd64, arm64, s390x, "386"] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: "386"
            goos: darwin
          - goarch: s390x
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: s390x
            goos: windows

    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22 # 可以指定编译使用的 Golang 版本
          binary_name: "pdb_proxy" # 可以指定二进制文件的名称
          extra_files: pdb_proxy.ini # 需要包含的额外文件